# Setup
title:        Liang shuaiyu's
tagline:      Edge of the Internet 世界一隅
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       sy.liang
  url:        http://www.liangsy.com
  email:      carlyleliang@gmail.com
  github:     bubbledoodle

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
